[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.1.0"
update_changelog_on_bump = true
changelog_incremental = true

[tool.commitizen.cz_conventional_commits]
bump_message = "chore(release): $version"
